runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /opgate
  script: main.app

- url: /_ah/push-handlers/.*
  script: main.app
  login: admin

libraries:
- name: ssl
  version: latest

automatic_scaling:
  max_idle_instances: 1
  max_instances: 1
  max_concurrent_requests: 2

#basic_scaling:
#  max_instances: 1

#[START env]
env_variables:
    PUBSUB_TOPIC: yanji
    GOOGLE_CLOUD_PROJECT: gategod-armor
    # This token is used to verify that requests originate from your
    # application. It can be any sufficiently random string.
    PUBSUB_VERIFICATION_TOKEN: 1234abcd
#[END env]
